workflows:
  expo-app-workflow:
    name: DemoExpo Build
    instance_type: mac_mini_m2  # Required for iOS builds
    working_directory: apps/demoexpo
    environment:
      node: latest
      vars:
        PACKAGE_NAME: "com.nikhil.demoexpo" # Change this
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          pnpm install # or npm install
      - name: Expo prebuild
        script: |
          # This generates the /ios and /android folders automatically on the build server
          npx expo prebuild --platform all
      - name: Build Android (APK)
        script: |
          cd android && ./gradlew assembleRelease
    #   - name: Build iOS (IPA)
    #     script: |
    #       # Note: iOS requires code signing setup in Codemagic UI to work
    #       xcode-project build-ipa --workspace ios/*.xcworkspace --scheme demoexpo
    # artifacts:
    #   - android/app/build/outputs/apk/release/*.apk
    #   - ios/build/remote/ipa/*.ipa
    # publishing:
    #   email:
    #     recipients:
    #       - your-email@example.com
